name: Build and Push Airtemp Workflows

on:
  repository_dispatch:
    types: [airtemp-update]
  workflow_dispatch:

jobs:

  airtemp-daily:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set container name
      run: echo "CONTAINER_NAME=task-at-pre-agg-daily" >> $GITHUB_ENV
    - name: Set Dockerfile location
      run: echo "DOCKERFILE=containers/airtemp/preliminary/aggregation/daily/Dockerfile" >> $GITHUB_ENV
    - name: Get date and hash
      run: echo "TAG=$(date --iso-8601)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    - name: Build container
      run: docker build . --file ${{ env.DOCKERFILE }} --tag ghcr.io/ikewai/${{ env.CONTAINER_NAME }}:${{ env.TAG }}
    - name: Log in to the container registry
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ secrets.PUSH_PACKAGE_USERNAME }}
        password: ${{ secrets.PUSH_PACKAGE_TOKEN }}
    - name: Tag the container as latest
      run: docker tag ghcr.io/ikewai/${{ env.CONTAINER_NAME }}:${{ env.TAG }} ghcr.io/ikewai/${{ env.CONTAINER_NAME }}:latest
    - name: Push the container
      run: docker push ghcr.io/ikewai/${{ env.CONTAINER_NAME }}:${{ env.TAG }} && docker push ghcr.io/ikewai/${{ env.CONTAINER_NAME }}:latest

  airtemp-monthly:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set container name
      run: echo "CONTAINER_NAME=task-at-pre-agg-monthly" >> $GITHUB_ENV
    - name: Set Dockerfile location
      run: echo "DOCKERFILE=containers/airtemp/preliminary/aggregation/monthly/Dockerfile" >> $GITHUB_ENV
    - name: Get date and hash
      run: echo "TAG=$(date --iso-8601)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    - name: Build container
      run: docker build . --file ${{ env.DOCKERFILE }} --tag ghcr.io/ikewai/${{ env.CONTAINER_NAME }}:${{ env.TAG }}
    - name: Log in to the container registry
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ secrets.PUSH_PACKAGE_USERNAME }}
        password: ${{ secrets.PUSH_PACKAGE_TOKEN }}
    - name: Tag the container as latest
      run: docker tag ghcr.io/ikewai/${{ env.CONTAINER_NAME }}:${{ env.TAG }} ghcr.io/ikewai/${{ env.CONTAINER_NAME }}:latest
    - name: Push the container
      run: docker push ghcr.io/ikewai/${{ env.CONTAINER_NAME }}:${{ env.TAG }} && docker push ghcr.io/ikewai/${{ env.CONTAINER_NAME }}:latest
