name: Build and Push task-base

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Get date and hash
      run: echo "DATE_AND_HASH=$(date --iso-8601)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    - name: Build task-base
      run: docker build . --file containers/core/task-base/Dockerfile --tag ghcr.io/ikewai/task-base:${{ env.DATE_AND_HASH }}
    - name: Log in to the container registry
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ secrets.PUSH_PACKAGE_USERNAME }}
        password: ${{ secrets.PUSH_PACKAGE_TOKEN }}
    - name: Push task-base
      run: docker push ghcr.io/ikewai/task-base:${{ env.DATE_AND_HASH }}
