name: Promote a Container to Prod

on:
  workflow_dispatch:
    inputs:
      containerName:
        description: 'Which container do you want to promote?'
        required: true
        type: choice
        options:
        - ikewai/task-at-pre-agg-daily
        - ikewai/task-at-pre-agg-monthly
        - ikewai/task-rf-pre-agg-daily
        - ikewai/task-rf-pre-agg-monthly
        - ikewai/task-sh-aq-hads-daily
        - ikewai/task-sh-aq-madis-daily
        - ikewai/task-sh-aq-nws-daily
        - ikewai/task-sh-aq-mesonet-daily
      repositoryName:
        description: 'On which package repository should the promotion occur?'
        required: true
        type: choice
        default: ghcr.io
        options:
        - ghcr.io
        
jobs:
  promote-container:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Get the selected container
      run: docker pull ${{ inputs.repositoryName }}/${{ inputs.containerName }}:latest
    - name: Tag the selected container as production-ready
      run: docker tag ${{ inputs.repositoryName }}/${{ inputs.containerName }}:latest ${{ inputs.repositoryName }}/${{ inputs.containerName }}:prod
    - name: Log in to the container registry
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ secrets.PUSH_PACKAGE_USERNAME }}
        password: ${{ secrets.PUSH_PACKAGE_TOKEN }}
    - name: Push the re-tagged container
      run: docker push ${{ inputs.repositoryName }}/${{ inputs.containerName }}:prod
