name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Task-Base
      run: docker build . --file containers/core/task-base/Dockerfile --tag ghcr.io/ikewai/task-base:$(date --iso-8601)-$(git rev-parse --short HEAD)
