name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Log in to repo
      run: echo $PUSH_PACKAGE_TOKEN | docker login -u=$PUSH_PACKAGE_USERNAME --password-stdin https://ghcr.io/ikewai
       
